/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Octagon AI API
 * API for Octagon AI's backend services.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import { customInstance } from '../../../services/custom-axios-instance';
import type { ErrorType } from '../../../services/custom-axios-instance';



export const evaluateCreate = (
    id: number,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/evaluate/${id}`, method: 'POST'
    },
      );
    }
  


export const getEvaluateCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof evaluateCreate>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof evaluateCreate>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof evaluateCreate>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  evaluateCreate(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EvaluateCreateMutationResult = NonNullable<Awaited<ReturnType<typeof evaluateCreate>>>
    
    export type EvaluateCreateMutationError = ErrorType<unknown>

    export const useEvaluateCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof evaluateCreate>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof evaluateCreate>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getEvaluateCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    