/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Octagon AI API
 * API for Octagon AI's backend services.
 * OpenAPI spec version: 1.0.0
 */

export type ApiAimodelsListParams = {
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
problem?: number;
/**
 * A search term.
 */
search?: string;
type?: number;
};
