/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Octagon AI API
 * API for Octagon AI's backend services.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedAIModel {
  /** @nullable */
  accuracy?: number | null;
  description?: string;
  /** @nullable */
  file?: string | null;
  readonly id?: number;
  /** @maxLength 255 */
  name?: string;
  /**
   * @maxLength 255
   * @nullable
   */
  nevermind_tag?: string | null;
  /** @nullable */
  problem?: number | null;
  readonly problem_name?: string;
  /** @nullable */
  type?: number | null;
  readonly type_name?: string;
}
