/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Octagon AI API
 * API for Octagon AI's backend services.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedType {
  description?: string;
  readonly id?: number;
  /** @maxLength 255 */
  name?: string;
}
